# Generated by Django 4.2.5 on 2023-09-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_choice_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
