# Generated by Django 4.2.5 on 2023-09-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_question_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='test',
        ),
    ]
