# Generated by Django 4.2.5 on 2023-09-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_choice_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='score',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
