# Generated by Django 4.2.5 on 2023-09-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_choice_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
